# fly.toml file generated for kmcphillips-annie-codes on 2022-11-12T11:00:13-05:00

app = "kmcphillips-annie-codes"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
builder = "heroku/buildpacks:20"

[env]
PORT = "8080"

[experimental]
allowed_public_ports = []
auto_rollback = true

[[services]]
internal_port = 8080
processes = ["app"]
protocol = "tcp"
script_checks = []
[services.concurrency]
hard_limit = 25
soft_limit = 20
type = "connections"

[[services.ports]]
force_https = true
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[[services.tcp_checks]]
grace_period = "1s"
interval = "15s"
restart_limit = 0
timeout = "2s"

[[services.http_checks]]
grace_period = "5s"
interval = 10000
method = "get"
path = "/ping"
protocol = "http"
restart_limit = 0
timeout = 2000
tls_skip_verify = false
